version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  dialect = "typescript"
  framework = "expo"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[exclude]
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "*.test.ts",
  "*.test.tsx"
]
