name: Build and Upload Internal Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Custom build name'
        required: false
        default: 'manual-build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Starting build process..."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Testing
        run: npm test

      - name: Building
        run: eas build --platform android --profile preview --local --output ./app-release.apk

      - name: Uploading
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.build_name || 'app-release' }}
          path: ./app-release.apk
