name: Android Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g expo-cli

    - name: Eject Expo app
      run: expo eject

    - name: Update AndroidManifest.xml
      run: |
        sed -i 's/package="com.iroan.manganess"//g' android/app/src/main/AndroidManifest.xml

    - name: Update build.gradle
      run: |
        sed -i 's/com.android.application/com.android.application"\n    id("com.android.library")/g' android/app/build.gradle
        echo "android.namespace='com.iroan.manganess'" >> android/app/build.gradle

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --warning-mode all

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
