name: Build and Upload Internal Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Custom build name'
        required: false
        default: 'manual-build'

jobs:
  start_build:
    name: Start Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install dependencies
        run: npm install

  testing:
    name: Testing
    needs: start_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        env:
          CI: true
        timeout-minutes: 10

  building:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ./app-release.apk
      - name: Upload APK for next job
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./app-release.apk
