name: iOS IPA Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli

    - name: Update app.json
      run: |
        jq '.expo.version = "${{ github.event.inputs.version }}" | .expo.ios.buildNumber = "${{ github.event.inputs.version }}"' app.json > temp.json && mv temp.json app.json

    - name: Configure EAS
      run: |
        echo '{"cli":{"version":">= 0.52.0"},"build":{"ios":{"simulator":true}}}' > eas.json

    - name: Build iOS IPA
      run: |
        eas build --platform ios --profile preview --non-interactive --no-wait

    - name: Download IPA
      run: |
        eas build:list --status finished --platform ios --non-interactive --json > builds.json
        BUILD_ID=$(jq -r '.[0].id' builds.json)
        eas build:download --platform ios --id $BUILD_ID --output ./app-preview.ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: app-preview
        path: ./app-preview.ipa

