name: iOS IPA Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g expo-cli

    - name: Update app.json with new version
      run: |
        jq '.expo.version = "${{ github.event.inputs.version }}" | .expo.ios.buildNumber = "${{ github.event.inputs.version }}"' app.json > temp.json && mv temp.json app.json

    - name: Start Expo build
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        expo build:ios --non-interactive --no-publish --type archive

    - name: Download IPA
      run: |
        mkdir build_artifacts
        expo url:ipa > ipa_url.txt
        EXPO_ARTIFACT_URL=$(cat ipa_url.txt)
        curl -o ./build_artifacts/app.ipa $EXPO_ARTIFACT_URL

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build_artifacts/app.ipa
