name: iOS Local Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g expo-cli

    - name: Update app.json
      run: |
        jq '.expo.version = "${{ github.event.inputs.version }}" | .expo.ios.buildNumber = "${{ github.event.inputs.version }}"' app.json > temp.json && mv temp.json app.json

    - name: Install Expo Development Build
      run: npx expo install expo-dev-client

    - name: Build iOS app locally
      run: |
        expo prebuild --platform ios
        cd ios
        pod install
        xcodebuild -workspace "$(ls *.xcworkspace | head -n 1)" -scheme "$(ls *.xcodeproj | sed 's/\.xcodeproj//')" -configuration Release -sdk iphonesimulator -arch x86_64 BUILD_DIR="build"

    - name: Package app
      run: |
        cd ios/build/Release-iphonesimulator
        mkdir Payload
        cp -r "$(ls *.app | head -n 1)" Payload
        zip -r app.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: app-local-build
        path: ios/build/Release-iphonesimulator/app.ipa